name: build

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      # - name: Run trivy with reviewdog output on the PR
      #   uses: reviewdog/action-trivy@14e16b394d55cc5cbbf0797b04fa5257adbe6e7a # v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     trivy_command: config # Change trivy command
      #     trivy_target: . # Change trivy target directory
      #     working_directory: "." # Change working directory
      #     level: info # Get more output from reviewdog
      #     reporter: github-pr-review # Change reviewdog reporter
      #     filter_mode: nofilter # Check all files, not just the diff
      #     fail_on_error: "false" # Fail action if errors are found
      #     trivy_flags: "--tf-vars dev.tfvars"

      # In addition to the Aqua one, run reviewdog Tfsec as well
      # as it provides more context and can pickup security issues
      # in underlying modules (more similar to locally running tfsec)
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@0f2a5fe5c3a5f044caa48a53bbd3dced5c04aef0 # v1.25.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # level: info # Get more output from reviewdog
          # reporter: github-pr-review # Change reviewdog reporter
          # filter_mode: nofilter # Check all files, not just the diff
          fail_on_error: true # Fail action if errors are found
          filter_mode: nofilter
          tfsec_flags: --ignore-hcl-errors --tfvars-file dev.tfvars
          
